### ISSUE TITLE
Can't create a labeled Point without also calling add_coordinates

### ISSUE THREAD

**Issue by Oddball777** [GraphingLib/GraphingLib#121]
### Fails :
Create point with only label
``` python
point = gl.Point(1, 2, "The label")

figure = gl.Figure()
figure.add_element(point)
figure.display()
```
``` text
  File "c:\Users\gcoulombe\Desktop\GraphingLib\derivative.py", line 67, in <module>
    figure.display()
  File "c:\Users\gcoulombe\Desktop\GraphingLib\graphinglib\figure.py", line 156, in display
    self._prepare_figure(legend=legend)
  File "c:\Users\gcoulombe\Desktop\GraphingLib\graphinglib\figure.py", line 119, in _prepare_figure
    element._plot_element(self._axes, z_order)
  File "c:\Users\gcoulombe\Desktop\GraphingLib\graphinglib\graph_elements.py", line 204, in _plot_element
    size = self.font_size if self.font_size != "same as figure" else None
                             ^^^^^^^^^^^^^^
AttributeError: 'Point' object has no attribute 'font_size'
```

Create point with only coordinates
``` python
point = gl.Point(1, 2)
point.add_coordinates()

figure = gl.Figure()
figure.add_element(point)
figure.display()
```
``` text
Traceback (most recent call last):
  File "c:\Users\gcoulombe\Desktop\GraphingLib\derivative.py", line 68, in <module>        
    figure.display()
  File "c:\Users\gcoulombe\Desktop\GraphingLib\graphinglib\figure.py", line 156, in display
    self._prepare_figure(legend=legend)
  File "c:\Users\gcoulombe\Desktop\GraphingLib\graphinglib\figure.py", line 119, in _prepare_figure
    element._plot_element(self._axes, z_order)
  File "c:\Users\gcoulombe\Desktop\GraphingLib\graphinglib\graph_elements.py", line 207, in _plot_element
    point_label = prefix + self.label + postfix
                  ~~~~~~~^~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
```

### Works :
Create a point with both a label and coordinates
``` python
point = gl.Point(1, 2, "The label")
point.add_coordinates()

figure = gl.Figure()
figure.add_element(point)
figure.display()
```
Create a point with neither
``` python
point = gl.Point(1, 2)

figure = gl.Figure()
figure.add_element(point)
figure.display()
```

### Identified problem
- Font_size parameter is defined only when add_coordinates is called but is used for the label as well.
- When creating the label's string, we don't check whether the user provided a ```label``` or if it's the default None.

### Potential solution
- Move ```label``` parameter to ```add_coordinates``` instead? Since this label isn't a legend label it's not inconsistent to move it out of the ```Point``` initializer. It would also be less misleading since for every other object, ```label``` in the initializer means adding something to the legend. We could also rename the ```add_coordinates``` to something more inclusive like ```add_label``` which contains the option to add a text label and/or the coordinates of the point. It would still include all the other parameters of the label like those for relative position, color, font size, etc.
- Three possible elifs for string creation: only label defined, only coordinates, or both.

**Comment by Oddball777** [comment]
These two cases still don't work:
Create a point with only coordinates (no text in label)
``` python
point = gl.Point(1, 2)
point.add_coordinates()

figure = gl.Figure()
figure.add_element(point)
figure.display()
```
Create a point with no label whatsoever
``` python
point = gl.Point(1, 2)

figure = gl.Figure()
figure.add_element(point)
figure.display()
```
